//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.16 at 02:15:29 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://occ.com/user/register", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.occ.user.register;
